### ISSUE TITLE
WebGL Export Error in Unity 2020

### ISSUE THREAD

**Issue by Blueteak** [xsolla/store-unity-sdk#59]
In Unity 2020 IL2CPP is the only export option for WebGL, and results in the following error during build compilation: 

```
Exception: IL2CPP error for method 'System.Void Microsoft.Extensions.Logging.Logger::Log(Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,TState,System.Exception,System.Func`3<TState,System.Exception,System.String>)' in assembly 'C:\Users\USERNAME\Documents\GitHub\PROJECT\Temp\StagingArea\Data\Managed\Microsoft.Extensions.Logging.dll'
System.InvalidOperationException: Unable to resolve a reference to the type 'System.Exception' in the assembly 'Microsoft.Extensions.Logging, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Does this type exist in a different assembly in the project?
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, TypeReference typeReference)
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments)
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType)
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context)
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context)
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context)
   at Unity.IL2CPP.GenericsCollection.GenericContextFreeVisitor.Visit(MethodDefinition methodDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context)
   at Unity.IL2CPP.GenericsCollection.GenericContextFreeVisitor.Visit(TypeDefinition typeDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context)
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context)
   at Unity.IL2CPP.GenericsCollection.GenericsCollector.Collect(PrimaryCollectionContext context, ReadOnlyCollection`1 assemblies)
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.Global.GenericsCollection.ProcessAllItems(GlobalPrimaryCollectionContext context, ReadOnlyCollection`1 items)
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.GlobalScheduledStepFunc`3.WorkerWrapper(WorkItemData`3 workerData)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at <433cbae83977409887e43d50043210d2>:0)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at <433cbae83977409887e43d50043210d2>:0)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String generatedCppOutputDirectory) (at <433cbae83977409887e43d50043210d2>:0)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.Boolean platformSupportsManagedDebugging) (at <433cbae83977409887e43d50043210d2>:0)
UnityEditorInternal.IL2CPPBuilder.Run () (at <433cbae83977409887e43d50043210d2>:0)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at <433cbae83977409887e43d50043210d2>:0)
UnityEditor.WebGL.WebGlBuildPostprocessor.CompileBuild (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:365)
UnityEditor.WebGL.WebGlBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:910)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <433cbae83977409887e43d50043210d2>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <433cbae83977409887e43d50043210d2>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

This occurs with both the Unity Asset Store version and the latest release on Github (v0.6.4.0)

**Comment by DenisRakhimovXsolla** [comment]
Unfortunately I cannot reproduce this, I checked the build in Unity 2020.3 (Windows and Mac) - everything is fine.
I suggest joining our discord channel for more quick communication: https://discord.gg/7BbYAMWu

**Comment by Blueteak** [comment]
Turns out it was an issue with Stripping Level set to High, it seems that the `XsollaBrowserLibrary.deps.json` uses `Microsoft.Extensions.Logging`, since the Xsolla browser isn't used in WebGL I was able to solve this issue (while retaining ability to use high stripping level), by setting the XsollaBrowserLibrary.dll to exclude WebGL and modify the `SinglePageBrowser2D.cs` file to #define out the first two variables (referencing `IXsollaBrowser`) for WebGL.

Thanks for the Discord link, will join!
