### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by limanskygames** [xsolla/store-unity-sdk#78]
```
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
       at com.xsolla.android.payments.caching.PayStationCache$setBrowserClients$2.onRenderProcessGone(PayStationCache.kt:106)
       at org.chromium.android_webview.AwContents.onRenderProcessGone(chromium-TrichromeWebViewGoogle.aab-stable-677810430:49)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:161)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```
       
       Xsolla 2.5.0
       Unity 2022.3.53f1

**Comment by AntonPetrov83** [comment]
We are facing a lot of these crashes too! Any estimates on a fix?

**Comment by olga-salina** [comment]
We have to update android payments library to 1.4.4 version to get rid of this crash

**Comment by AlexSergPosp** [comment]
We have a lot of these crashes too.

**Comment by olga-salina** [comment]
@AlexSergPosp  The same solution. Only update to the 1.4.4 version will help

**Comment by olga-salina** [comment]
@AntonPetrov83  
If you are using Xsolla Unity SDK you can just update it to 2.5.1 version

**Comment by AntonPetrov83** [comment]
I can confirm it's fixed in 2.5.1
